services:
  db:
    image: mysql:8
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ajouevent
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PW}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -p${DB_ROOT_PW}"]
      interval: 5s
      timeout: 30s
      retries: 5

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 30s
      retries: 5

  backend:
    # aws ecr 접속 가능한
    image: 879084048693.dkr.ecr.ap-northeast-2.amazonaws.com/my_image_hub:latest
    ports:
      - "443:8443"
    environment:
      SPRING_PROFILES_ACTIVE: prop
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      KEYSTORE_PASSWORD: ${KEYSTORE_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy