name: Deploy to EC2

on:
  workflow_dispatch:
#  push:
#      branches:
#        - CI_ecr-test
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_DEPLOY_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key

      - name: Run remote deploy.sh on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/deploy_key deploybot@43.200.133.31
